// Dados estáticos dos veículos (snapshot do catálogo oficial Motochefe Itaim)
// Sem dependência de backend — edite este arquivo para atualizar o catálogo.

const WHATSAPP = "5511948711047";
const INSTAGRAM = "https://www.instagram.com/motochefe.itaim/";
const FACEBOOK = "https://www.facebook.com/profile.php?id=61562114171718";
const MAPS_URL = "https://www.google.com/maps/search/?api=1&query=Rua+João+Cachoeira+1387+Itaim+Bibi+São+Paulo";
const LOGO_URL = "https://motochefeitaim.com.br/wp-content/uploads/2024/07/Logo-Branco-1024x422.webp";
const HERO_VIDEO = "https://motochefeitaim.com.br/wp-content/uploads/2024/08/copy_858DBB0B-331D-4BF6-BDB2-CD21B0F731C7.mp4";

const waLink = (name, price, url) =>
  `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(
    `Quero mais informações.\n\n*${name}*\n*Preço:* ${price ? "R$ " + Number(price).toLocaleString("pt-BR") : "Sob Consulta"}\n*URL:* ${url || ""}\n\nObrigado!`
  )}`;

const VEHICLES = [
  { name: "MC Mia", category: "Autopropelidos", price: 9990, power_w: 1000, range_km: 40, top_speed_kmh: 32, description: "A Scooter Elétrica MIA 1000w da Moto Chefe é a opção ideal para você que procura mobilidade prática, econômica e sustentável!", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/mia.webp", product_url: "https://motochefeitaim.com.br/product/mc-mia-1000w-autopropelido-sem-cnh/", featured: true },
  { name: "MC Jet Max", category: "Autopropelidos", price: 12990, power_w: 1000, range_km: 40, top_speed_kmh: 32, description: "A Jet Max combina design robusto e moderno com tecnologia inteligente para o dia a dia. Motor de 1000W, 32 km/h, bateria de lítio 60V 30Ah de longa duração. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/11/jetmax_product.webp", product_url: "https://motochefeitaim.com.br/product/motochefe-jetmax-1000w-autopropelido-sem-cnh-copia/", featured: true },
  { name: "MC X12", category: "Autopropelidos", price: 10990, power_w: 1000, range_km: 50, top_speed_kmh: 32, description: "O modelo X12 é estiloso, moderno e inovador. Ideal para o dia a dia e momentos de lazer, com suspensão dupla e banco diferenciado. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/x12_product.webp", product_url: "https://motochefeitaim.com.br/product/scooter-eletrica-x12-1000w-autopropelido-sem-cnh/", featured: true },
  { name: "MC Giga", category: "Autopropelidos", price: null, power_w: 1000, range_km: 50, top_speed_kmh: 32, description: "Estilo e design. Scooter elétrica autopropelida com 1000W e 50 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/11/mod_product_giga.webp", product_url: "https://itaim.motochefe.com.br", featured: true },
  { name: "MC Joy Tri", category: "Triciclos, Autopropelidos", price: null, power_w: 600, range_km: 40, top_speed_kmh: 32, description: "Conforto, mobilidade e design. Triciclo elétrico com 600W e 55 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/joytri_w.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC X15", category: "Triciclos, Ciclomotores", price: null, power_w: 3000, range_km: 45, top_speed_kmh: 50, description: "Potência, design e agilidade. Scooter elétrica de 3000W que atinge 50 km/h. Exige CNH e emplacamento.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/x15.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC VED", category: "Triciclos, Autopropelidos", price: 15290, power_w: 1000, range_km: 45, top_speed_kmh: 32, description: "A VED 1000W oferece uma maneira ecologicamente correta de se locomover e prioriza o conforto.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/11/ved_product.webp", product_url: "https://motochefeitaim.com.br/product/triciclo-ventane-1000w-autopropelido-sem-cnh/" },
  { name: "MC Big Tri", category: "Triciclos, Autopropelidos", price: null, power_w: 1000, range_km: 45, top_speed_kmh: 32, description: "Estilo, conforto e dia a dia. Triciclo elétrico com 1000W e 55 km de autonomia.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/big_tiny.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Mia Tri", category: "Triciclos, Autopropelidos", price: 12490, power_w: 800, range_km: 40, top_speed_kmh: 32, description: "Triciclo ideal para quem busca alternativa prática e sustentável, sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/miatri2_.webp", product_url: "https://motochefeitaim.com.br/product/triciclo-mc-mia-800w-autopropelido-sem-cnh/" },
  { name: "MC Space", category: "E-bikes", price: null, power_w: 750, range_km: 35, top_speed_kmh: 32, description: "Estilo, mobilidade e dia a dia. Bicicleta elétrica com 750W e 35 km de autonomia. Quadro robusto, sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/space_prodc.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Grid", category: "E-bikes", price: null, power_w: 750, range_km: 35, top_speed_kmh: 32, description: "Estilo, design e urban. Bicicleta elétrica com 750W e 35 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/grid.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Style", category: "E-bikes", price: 10490, power_w: 750, range_km: 35, top_speed_kmh: 32, description: "Bicicleta Elétrica STYLE com motor de 750w e quadro em aço carbono para durabilidade e resistência. Desempenho potente para seus passeios.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/Style_prodc.webp", product_url: "https://motochefeitaim.com.br/product/bicicleta-eletrica-style-750w-ventane-motors/" },
  { name: "MC Liberty", category: "E-bikes", price: null, power_w: 600, range_km: 35, top_speed_kmh: 32, description: "Estilo, design e dia a dia. Scooter elétrica autopropelida com 600W e 40 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/liberty_produto_front.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Roma", category: "Ciclomotores", price: null, power_w: 3000, range_km: 50, top_speed_kmh: 50, description: "Conforto, design e clássica. Scooter elétrica de 3000W que atinge 50 km/h. Exige CNH e emplacamento.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/roma_prodc.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC 20", category: "Ciclomotores", price: null, power_w: 2000, range_km: 50, top_speed_kmh: 50, description: "Estilo, potência e autonomia. Scooter elétrica de 2000W que atige 50 km/h com 80 km de autonomia. Exige CNH e emplacamento.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/mc20.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC X11", category: "Ciclomotores", price: 11990, power_w: 2000, range_km: 50, top_speed_kmh: 50, description: "O modelo X11 é estiloso e potente. Atinge 50 km/h com motor de 2000W e 80 km de autonomia. Exige CNH e emplacamento.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/x11.webp", product_url: "https://motochefeitaim.com.br/product/scooter-eletrica-mc-x11-3000w/" },
  { name: "MC Soma", category: "Autopropelidos", price: 8990, power_w: 1000, range_km: 40, top_speed_kmh: 32, description: "SOMA une estilo, modernidade e inovação. Suspensão dupla e banco confortável, bateria de lítio removível. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/soma_prod3.webp", product_url: "https://motochefeitaim.com.br/product/mc-soma-1000w-autopropelido-sem-cnh/" },
  { name: "MC Sofia", category: "Autopropelidos", price: null, power_w: 1000, range_km: 45, top_speed_kmh: 32, description: "Estilo, design e clássica. Scooter elétrica autopropelida com 1000W e 45 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/11/sofia_product-1.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC 20 Mini", category: "Autopropelidos", price: null, power_w: 1000, range_km: 45, top_speed_kmh: 32, description: "Mobilidade, dia a dia e economia. Scooter elétrica autopropelida com 1000W e 45 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/20mini2_tiny_product.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Bob", category: "Autopropelidos", price: null, power_w: 1000, range_km: 40, top_speed_kmh: 32, description: "Conforto, mobilidade e economia. Scooter elétrica autopropelida com 1000W e 40 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/Camada-1_c2_tiny2.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Ret", category: "Autopropelidos", price: null, power_w: 1000, range_km: 40, top_speed_kmh: 32, description: "Conforto, mobilidade e design. Scooter elétrica autopropelida com 1000W e 40 km de autonomia. Sem necessidade de CNH.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/11/ret_.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Joy Super", category: "Autopropelidos", price: 7490, power_w: 800, range_km: 40, top_speed_kmh: 32, description: "A SUPER Joy 800W oferece mobilidade, conforto, economia e agilidade. Perfeita para o dia a dia.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/JOY-SUPER-1-1_front.webp", product_url: "https://motochefeitaim.com.br/product/mc-super-joy-800w-autopropelido-sem-cnh/" },
  { name: "MC Joyzinha", category: "Autopropelidos", price: null, power_w: 600, range_km: 40, top_speed_kmh: 32, description: "Mobilidade, leveza e dia a dia. Scooter elétrica autopropelida com 600W e 40 km de autonomia.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/joy.webp", product_url: "https://itaim.motochefe.com.br" },
  { name: "MC Jet", category: "Autopropelidos", price: 10990, power_w: 1000, range_km: 40, top_speed_kmh: 32, description: "Se você precisa de um meio de transporte no dia a dia e não quer tirar carteira, o Jet é a escolha certa.", image_url: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/jet.webp", product_url: "https://motochefeitaim.com.br/product/scooter-eletrica-jet-1000w-autopropelido-sem-cnh/" }
];

const CATEGORIES = [
  { name: "AUTOPROPELIDOS", count: "13 Modelos", image: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/mia.webp", filter: "Autopropelidos" },
  { name: "CICLOMOTORES", count: "4 Modelos", image: "https://itaim.motochefe.com.br/wp-content/uploads/2024/09/x11.webp", filter: "Ciclomotores" },
  { name: "TRICICLOS", count: "4 Modelos", image: "https://itaim.motochefe.com.br/wp-content/uploads/2025/11/ved_product.webp", filter: "Triciclos" },
  { name: "E-BIKES", count: "3 Modelos", image: "https://itaim.motochefe.com.br/wp-content/uploads/2025/10/Style_prodc.webp", filter: "E-bikes" }
];

// Helper para formatar preço
const fmtPrice = (v) => v ? "R$ " + Number(v).toLocaleString("pt-BR") : null;
